version: '3'

volumes:
  grafana-data:
    driver: local
  prometheus-db:
    driver: local

networks:
  frontend:
    external: true
  backend:
    external: true

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    networks:
      - frontend
      - backend
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - backend
    volumes:
      - /etc/prometheus:/etc/prometheus
      - prometheus-db:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"